# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rds < Formula
  desc "RobotDomainSearch CLI — domain intelligence from your terminal"
  homepage "https://robotdomainsearch.com"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robotdomainsearch/releases/releases/download/v0.1.1/rds_darwin_amd64.tar.gz"
      sha256 "93c4d23e274bb7f07bb7fb45d775904dcf2786acceedd19c87a1912ff736f5b5"

      define_method(:install) do
        bin.install "rds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robotdomainsearch/releases/releases/download/v0.1.1/rds_darwin_arm64.tar.gz"
      sha256 "ec0d29cfc31eae346eff595515f523c90b8db9a4759b9c3433e85450c31f05f6"

      define_method(:install) do
        bin.install "rds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robotdomainsearch/releases/releases/download/v0.1.1/rds_linux_amd64.tar.gz"
      sha256 "8fa5bf7e638b01ad969fc38e6dafda8c1f32cfe2bb4ce25d82b8b26cc83a764a"
      define_method(:install) do
        bin.install "rds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robotdomainsearch/releases/releases/download/v0.1.1/rds_linux_arm64.tar.gz"
      sha256 "f1e052208da589b79a3b0344a1aab14dc733b9f7d22291820873d148b0ee8f93"
      define_method(:install) do
        bin.install "rds"
      end
    end
  end

  test do
    system "#{bin}/rds", "version"
  end
end
