# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rds < Formula
  desc "RobotDomainSearch CLI — domain intelligence from your terminal"
  homepage "https://robotdomainsearch.com"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robotdomainsearch/releases/releases/download/v0.1.1/rds_darwin_amd64.tar.gz"
      sha256 "1421f5e6ea3fab89a3ae3f42a5ae5d3c979df08e56ca7ee74584c5174c9348f7"

      define_method(:install) do
        bin.install "rds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robotdomainsearch/releases/releases/download/v0.1.1/rds_darwin_arm64.tar.gz"
      sha256 "d5d0c99a02d3ce8b94ca7c79ce49af2d3bf519cc5754260ed17fbbc592043ab4"

      define_method(:install) do
        bin.install "rds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robotdomainsearch/releases/releases/download/v0.1.1/rds_linux_amd64.tar.gz"
      sha256 "2a193ccde20024229264bcba83222b533446d61b517a9294fe988862e640de27"
      define_method(:install) do
        bin.install "rds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robotdomainsearch/releases/releases/download/v0.1.1/rds_linux_arm64.tar.gz"
      sha256 "faa55e9c0ee0002405f43ddf2b0904c744b4ae935d5c4fb73b56d16467ab296a"
      define_method(:install) do
        bin.install "rds"
      end
    end
  end

  test do
    system "#{bin}/rds", "version"
  end
end
