# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rds < Formula
  desc "RobotDomainSearch CLI — domain intelligence from your terminal"
  homepage "https://robotdomainsearch.com"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robotdomainsearch/releases/releases/download/v0.2.0/rds_darwin_amd64.tar.gz"
      sha256 "1a7d9984b97a794f58233d5603f0d9965e2fa050f4973b75c342c4abba165c35"

      define_method(:install) do
        bin.install "rds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robotdomainsearch/releases/releases/download/v0.2.0/rds_darwin_arm64.tar.gz"
      sha256 "42e2c30b06d75fae2679a4b5b8ccc6c8c08fe1c6f1a55d58930779f99070c0c2"

      define_method(:install) do
        bin.install "rds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robotdomainsearch/releases/releases/download/v0.2.0/rds_linux_amd64.tar.gz"
      sha256 "73c68ce7f156b07f6c16a80b14e98da0d84efa82dde2177ee580a3cc2e3b791a"
      define_method(:install) do
        bin.install "rds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robotdomainsearch/releases/releases/download/v0.2.0/rds_linux_arm64.tar.gz"
      sha256 "eec55d7380042d1b47b6a1bbd4cb1e2951d792c11482d9c79c2f47bc0866ef13"
      define_method(:install) do
        bin.install "rds"
      end
    end
  end

  test do
    system "#{bin}/rds", "version"
  end
end
